<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Referral Slip</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #0056b3;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #0056b3;
            font-size: 20px;
            margin: 5px 0;
        }
        .header p {
            margin: 2px 0;
            color: #666;
        }
        .auth-block {
            float: right;
            border: 1px solid #28a745;
            background-color: #f8fff8;
            padding: 10px;
            border-radius: 5px;
            text-align: left;
            width: 250px;
        }
        .auth-block h3 {
            margin-top: 0;
            color: #28a745;
            font-size: 14px;
            border-bottom: 1px solid #28a745;
            padding-bottom: 3px;
        }
        .clear {
            clear: both;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
            width: 30%;
        }
        .section-title {
            background-color: #0056b3;
            color: #fff;
            padding: 5px 10px;
            font-size: 14px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        .footer {
            margin-top: 30px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
            font-size: 10px;
            color: #777;
        }
        .content-box {
            border: 1px solid #eee;
            padding: 10px;
            margin-bottom: 10px;
            min-height: 50px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>CLINICAL REFERRAL SLIP</h1>
        <p>Referral ID: REF-{{ $referral->id }} | Date: {{ $referral->created_at->format('d M Y') }}</p>
    </div>

    @if($referral->authorization)
    <div class="auth-block">
        <h3>Authorization details</h3>
        <p><strong>Code:</strong> {{ $referral->authorization->authorization_code }}</p>
        <p><strong>Expiry:</strong> {{ $referral->authorization->expires_at ? $referral->authorization->expires_at->format('d M Y') : 'N/A' }}</p>
        <p><strong>Generated By:</strong> {{ $referral->authorization->approver->name ?? 'System' }}</p>
    </div>
    @endif
    
    <div style="float: left; width: 60%;">
        <table>
            <tr>
                <th>Referred From:</th>
                <td>{{ $referral->fromFacility->name ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>Referred To:</th>
                <td>{{ $referral->toFacility->name ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="clear"></div>

    <div class="section-title">PATIENT DEMOGRAPHICS</div>
    @php
        $patient = $referral->encounter->patient ?? null;
        $enrolleeDetails = $patient ? $patient->enrolleeDetails : null;
    @endphp
    <table>
        <tr>
            <th>Name:</th>
            <td>{{ $enrolleeDetails->fullname ?? 'N/A' }}</td>
            <th>Age/DOB:</th>
            <td>{{ $enrolleeDetails->dob ? \Carbon\Carbon::parse($enrolleeDetails->dob)->age . ' yrs' : 'N/A' }}</td>
        </tr>
        <tr>
            <th>Sex:</th>
            <td>{{ ucfirst($enrolleeDetails->gender ?? 'N/A') }}</td>
            <th>Phone:</th>
            <td>{{ $enrolleeDetails->phone_no ?? ($enrolleeDetails->phone ?? 'N/A') }}</td>
        </tr>
        <tr>
            <th>Enrollee ID:</th>
            <td>{{ $patient->enrollee_number ?? 'N/A' }}</td>
            <th>File Number:</th>
            <td>{{ $patient->file_number ?? 'N/A' }}</td>
        </tr>
    </table>

    <div class="section-title">REASON FOR REFERRAL</div>
    <div class="content-box">
        <p><strong>Requested Service/Specialist:</strong> {{ $referral->serviceItem->name ?? 'General Referral' }}</p>
        <p>{{ $referral->reason }}</p>
    </div>

    <div class="section-title">CLINICAL INFORMATION</div>
    
    @php
        $consultations = $referral->encounter ? $referral->encounter->consultations : collect([]);
    @endphp

    @if($consultations->count() > 0)
        @foreach($consultations as $consultation)
            <div class="content-box">
                <p><strong>Presenting Complaints:</strong><br/>
                {{ $consultation->presenting_complaints ?? 'N/A' }}</p>
                
                <p><strong>Clinical Findings / Examination:</strong><br/>
                {{ $consultation->clinical_note ?? 'N/A' }}</p>
                
                <p><strong>Diagnoses:</strong></p>
                <ul>
                @if($consultation->diagnoses && $consultation->diagnoses->count() > 0)
                    @foreach($consultation->diagnoses as $diagnosis)
                        <li>[{{ $diagnosis->icdCode->code ?? 'N/A' }}] {{ $diagnosis->icdCode->description ?? 'N/A' }} - <em>{{ ucfirst($diagnosis->diagnosis_type ?? 'primary') }}</em></li>
                    @endforeach
                @else
                    <li>No diagnoses recorded.</li>
                @endif
                </ul>
            </div>
        @endforeach
    @else
        <div class="content-box">
            <p>No clinical consultations recorded for this referral encounter.</p>
        </div>
    @endif

    <div style="margin-top: 40px; width: 100%;">
        <div style="float: left; width: 50%; text-align: center;">
            <p>_____________________________________</p>
            <p><strong>Referring Doctor/Officer</strong><br/>Date: {{ $referral->created_at->format('d M Y') }}</p>
        </div>
        <div style="float: right; width: 50%; text-align: center;">
            <p>_____________________________________</p>
            <p><strong>Receiving Facility Signature/Stamp</strong><br/>Date: _______________</p>
        </div>
        <div class="clear"></div>
    </div>

    <div class="footer">
        Generated on {{ now()->format('d M Y H:i') }} | This document is electronically generated and requires an authorization code to be valid.
    </div>

</body>
</html>
